# First Stage: to install and build dependences
FROM node:14 AS build
WORKDIR /project
COPY . ./
RUN npm install
COPY . ./
RUN npm run build api

# Second Stage: Setup command to run the app using linghtweight node image
FROM node:14-alpine
WORKDIR /project
COPY --from=build /project ./
EXPOSE 3333
CMD [ "npm", 'run', "start:api"]
