# Docker-compose version
version: '3.6'
# Services/Containers to be run
services: 
  # Name of the first service/container
  front:
    image: "articles-fe-${BUILD_ENV}"
    build: 
      context: .
      target: "${BUILD_ENV}"
      dockerfile: ./client-image/
    volumes:
      - ./apps/articles-chrono/src:/apps/articles-chrono/src
    ports:
      - 4200:4200
    command: npm run start:client
  # Name of the second service/container
  api:
    image: "sb/articles-api:${BUILD_ENV}"
    build: 
      context: .
      target: "${BUILD_ENV}"
      dockerfile: ./api-image/
    volumes:
      - ./apps/api/src:/apps/api/src
    ports:
      - 3333:3333
    links:
      - mongodb
    command: npm run start:api
  # Name of the third service/container
  mongodb: 
    image: mongo:latest
    environment: 
      - MONGODB_DATABASE="nest"
    volumes:
      - /data/mongodb/db:/data/db
    ports:
      - 27017:27017